#должно соответствовать версии на сервере
version: '3'
services:
  bot:
    container_name: my_bot
    build: ./bot
    ports:
      - '8000:80'
    environment:
      TOKEN: ${TOKEN}
      BOT_ID: ${BOT_ID}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./bot/resources:/usr/src/app/resources
    depends_on:
      - redis_db
      - postgres_db

  redis_db:
    container_name: redis_db
    image: redis:7.0.5-alpine
    ports:
      - '6279:6279'
    volumes:
      - ./redis_data:/data

  postgres_db:
    container_name: postgres_db
    image: postgres:15.1-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
      PGADMIN_DEFAULT_PASSWORD: just_pass




