#должно соответствовать версии на сервере
version: '3'
services:
  bot:
    container_name: my_bot
    build: ./bot
    ports:
      - '8000:80'
    environment:
      TOKEN: ${TOKEN}
      BOT_ID: ${BOT_ID}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./bot/resources:/usr/src/app/resources
    depends_on:
      - redis_db
      - postgres_db

  redis_db:
    container_name: redis_db
    image: redis:7.0.5-alpine
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    ports:
      - '6379:6379'
    volumes:
      - ./redis_data:/data

  postgres_db:
    container_name: postgres_db
    image: postgres:15.1-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: '--auth-host=scram-sha-256 --auth-local=scram-sha-256'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}




